from domain.models import Editorial, ProblemData


class MarkdownFormatter:
    @staticmethod
    def format(editorial: Editorial, problem: ProblemData) -> str:
        """
        Render an editorial into a Markdown document with a metadata header
        and attribution footer.

        The output includes:
        - problem and contest identifiers
        - title and URL
        - optional editorial source URL
        - the original solution text without modification
        """
        lines = []

        # Metadata header
        lines.append("---")
        lines.append(f"Problem: {problem.identifier.problem}")
        lines.append(f"Contest: {problem.identifier.contest_id}")
        lines.append(f"title: {problem.title}")
        lines.append(f"Link: {problem.url}")
        if editorial.source_url:
            lines.append(f"Editorial: {editorial.source_url}")
        lines.append("---")
        lines.append("")

        # Original editorial text (preserves all formatting)
        lines.append(editorial.solution_text)
        lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by codeforces-editorial-finder*")
        lines.append("")

        return "\n".join(lines)


def format_editorial_markdown(editorial: Editorial, problem: ProblemData) -> str:
    return MarkdownFormatter.format(editorial, problem)
