"""Markdown formatter for editorials."""

from codeforces_editorial.models import Editorial, ProblemData


class MarkdownFormatter:
    """Formats editorial as Markdown."""

    @staticmethod
    def format(editorial: Editorial, problem: ProblemData) -> str:
        """
        Format editorial as Markdown.

        Args:
            editorial: Editorial to format
            problem: Problem data

        Returns:
            Formatted Markdown string
        """
        lines = []

        # Header
        lines.append(f"# Problem {problem.identifier.full_id}: {problem.title}")
        lines.append("")

        # Problem link
        lines.append("## Problem Link")
        lines.append(f"[{problem.url}]({problem.url})")
        lines.append("")

        # Approach
        if editorial.approach:
            lines.append("## Approach")
            lines.append(editorial.approach)
            lines.append("")

        # Algorithm
        if editorial.algorithm:
            lines.append("## Algorithm/Data Structure")
            lines.append(editorial.algorithm)
            lines.append("")

        # Complexity
        if editorial.time_complexity or editorial.space_complexity:
            lines.append("## Complexity")
            if editorial.time_complexity:
                lines.append(f"- **Time**: {editorial.time_complexity}")
            if editorial.space_complexity:
                lines.append(f"- **Space**: {editorial.space_complexity}")
            lines.append("")

        # Solution
        lines.append("## Solution")
        lines.append(editorial.solution_text)
        lines.append("")

        # Code snippets
        if editorial.code_snippets:
            lines.append("## Code")
            for snippet in editorial.code_snippets:
                if snippet.description:
                    lines.append(f"### {snippet.description}")
                lines.append(f"```{snippet.language}")
                lines.append(snippet.code)
                lines.append("```")
                lines.append("")

        # Hints
        if editorial.hints:
            lines.append("## Hints")
            for i, hint in enumerate(editorial.hints, 1):
                lines.append(f"{i}. {hint}")
            lines.append("")

        # Notes
        if editorial.notes:
            lines.append("## Notes")
            lines.append(editorial.notes)
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by codeforces-editorial-finder*")
        if editorial.source_url:
            lines.append(f"*Source: {editorial.source_url}*")
        lines.append("")

        return "\n".join(lines)


def format_editorial_markdown(editorial: Editorial, problem: ProblemData) -> str:
    """
    Convenience function to format editorial.

    Args:
        editorial: Editorial
        problem: Problem data

    Returns:
        Markdown string
    """
    return MarkdownFormatter.format(editorial, problem)
